---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
   - name: Obtain Creds
     include_vars: secrets.yaml 

   - name: Define Provider
     set_fact:
      provider:
       host: "{{ inventory_hostname }}"
       username: "{{ creds['username'] }}"
       password: "{{ creds['password'] }}"
       auth_pass: "{{ creds['auth_pass'] }}"

   - name: RUN 'SHOW VERSION'
     ios_command:
      provider: "{{ provider}}"
      authorize: yes
      commands:
       - show version
     register: ver
   - debug: var=ver.stdout_lines

   - ios_command:
      provider: "{{ provider}}"
      commands:
       - show interfaces status
     register: stat
   - debug: var=stat.stdout_lines
